### ISSUE TITLE
Support for Describe queries

### ISSUE THREAD

**Issue by mommi84** [AKSW/KBox#5]
Currently, `DESCRIBE` queries aren't supported.

```
$ java -Xmx8g -jar kbox-v0.0.1-alpha2.jar -sparql "DESCRIBE <http://dbpedia.org/resource/Tom_Jones_(singer)>" -graph "http://dbpedia.org/2015-10/en/full"
11:53:23 19 Dec 2016 - [main] INFO  org.aksw.kbox.kibe.KBox  - Error exectuting query.
com.hp.hpl.jena.query.QueryExecException: Attempt to have ResultSet from a DESCRIBE query
	at com.hp.hpl.jena.sparql.engine.QueryExecutionBase.execSelect(QueryExecutionBase.java:182)
	at org.aksw.kbox.kibe.tdb.TDB.query(TDB.java:47)
	at org.aksw.kbox.kibe.tdb.TDB.query(TDB.java:23)
	at org.aksw.kbox.kibe.KBox.query(KBox.java:427)
	at org.aksw.kbox.kibe.KBox.main(KBox.java:120)
```

One can use this instead:
```
SELECT * WHERE {
    { <http://dbpedia.org/resource/Tom_Jones_(singer)> ?p ?o }
    UNION { ?s ?p <http://dbpedia.org/resource/Tom_Jones_(singer)> }
}
```

**Comment by digamarx** [comment]
Implemented support to Describe, Ask and Construct queries
