### ISSUE TITLE
Error "java.io.EOFException: Unexpected end of ZLIB input stream"

### ISSUE THREAD

**Issue by omarsmak** [AKSW/KBox#8]
Hello team,

I have managed to download DBpedia 2015_10 using kbox, however after it finished downloading started to install, it produced the following error in the logs:
```
22:43:09 10 May 2017 - [main] ERROR org.aksw.kbox.kibe.Main  - Error installing the Knowledge Bases.
org.askw.kbox.kns.exception.ResourceDereferencingException: The resource http://dbpedia.org/2015_10/en/full could not be derecerenced.
        at org.aksw.kbox.kns.KBox.getResource(KBox.java:267)
        at org.aksw.kbox.kibe.KBox.getKowledgebases(KBox.java:700)
        at org.aksw.kbox.kibe.KBox.createModel(KBox.java:686)
        at org.aksw.kbox.kibe.Main.main(Main.java:380)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at org.aksw.kbox.utils.ZIPUtil.copy(ZIPUtil.java:78)
        at org.aksw.kbox.utils.ZIPUtil.copy(ZIPUtil.java:91)
        at org.aksw.kbox.utils.ZIPUtil.unzip(ZIPUtil.java:106)
        at org.aksw.kbox.apple.ZipAppInstall.install(ZipAppInstall.java:21)
        at org.aksw.kbox.apple.AbstractInstall.install(AbstractInstall.java:28)
        at org.aksw.kbox.apple.KBox.install(KBox.java:92)
        at org.aksw.kbox.kns.KBox.getResource(KBox.java:265)
        ... 3 more
```

**Comment by digamarx** [comment]
We end-up facing some issues with our servers on March last year that was solved by replicating our server in different globe areas.
